### PR TITLE
Use esp-idf vfs

### PR DESCRIPTION
**Pull request by annejan**
This branch by @rnplus seems like a good way to bolt the esp-idf vfs under micropython in stead of its default vfs.

### CODE REVIEW

**Comment by Spritetm** [comment]
Erm... all the code in there is dummy'ed out, is that intentional?

**Comment by annejan** [comment]
Sorry for lack of intro from irc .. this is not yet ready code
Just a start . . 
So yes, it seems it is intentional 😉

**Review by basvs — APPROVED** [review]
Reviewing my own code…

mount(), umount() and mkfs() are not supported (although mount() is used as trigger to mount the filesystem on /) → this is all intentional

open() is a bit verbose when the open fails.
we might want to lower this one day..

**Comment by basvs** [comment]
previous comments mentioned stubs. there shouldn't be any stubs anymore.

**Pull request merged**
