### PR TITLE
Remove old wifi module and replace with updated one

### PR DESCRIPTION
**Pull request by Roosted7**
UNTESTED!!!

Please test first, and check if removal of force_enable()  broke something elsewhere

### CODE REVIEW

**Comment by annejan** [comment]
The wifi module is just a convenience thing for connecting with wifi.init()

The easywifi doesn't seem to be a replacement for that functionality . . or . . am I missing something?

**Review by annejan — CHANGES_REQUESTED** [review]
Please don't delete the wifi module, 30+ apps in Hatchery are currently using it . .

**Comment by renzenicolai** [comment]
Leave it as is please.

**Comment by Roosted7** [comment]
Should then just leave the wifi module as is :)

**Comment by basvs** [comment]
@Roosted7 could you update your merge request or close this merge request?

**Pull request closed without merging**
