### PR TITLE
Return to home with start in launcher

### PR DESCRIPTION
**Pull request by Roosted7**

### CODE REVIEW

**Comment by renzenicolai** [comment]
This was removed in order to avoid confusion when holding a finger on the start button returns back to home directly after starting the launcher. Also removed to avoid confusion when a user tries to start an app by pressing start...

My advice is to not merge this pr.

**Comment by Roosted7** [comment]
I kinda agree, but if more people start complaining with 'huh my launcher is br0ken?!' we should consider this because it is indeed more consistent (which is important for a ui).

What do @sebastius and @niekproductions think of this?

**Comment by Kartoffel** [comment]
I agree with @rnplus, merging seems like a bad UX decision

**Comment by renzenicolai** [comment]
Both reviewers agree that this change is not a good idea. This PR will thus be closed.

**Comment by sebastius** [comment]
This is not something you want in terms of UX.

**Pull request closed without merging**
