### PR TITLE
Only draw the screen when not starting any services.

### PR DESCRIPTION
**Pull request by basvs**

### CODE REVIEW

**Comment by Roosted7** [comment]
After the PR the splash does not update unless services are active or the splash is going to sleep

**Comment by basvs** [comment]
Hmm, did you test it with all 3 commits? (see my comments on irc)
I was hoping I fixed that in the last 2 commits this afternoon. But I have to admit I didn't have any time to test the new commits.

**Comment by Roosted7** [comment]
I tested your branch and it's not fixed. I assume the variable 'have_services' does not report back what your code expects?

On Sat, 3 Mar 2018, 23:04 basvs, <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm, did you test it with all 3 commits? (see my comments on irc)
I was hoping I fixed that in the last 2 commits this afternoon. But I have to admit I didn't have any time to test the new commits.

**Comment by basvs** [comment]
hmm, did some testing, but the patch seems to work as intended.. But I did have some problems with the build-system. I had to do a full rebuild to repack the python modules. (it didn't pick up changes in these files)

**Pull request merged**
