### PR TITLE
Remove deprecated led function

### PR DESCRIPTION
**Pull request by Roosted7**

### CODE REVIEW

**Comment by Roosted7** [comment]
So this function is not deprecated @basvs ?

**Comment by basvs** [comment]
The original C method is deprecated. Don't know what's wise to do. Deprecate the micropython method as well?

@annejan Is this method used a lot in the hatchery?

**Review by basvs — COMMENTED** [review]
The patch itself is correct. :-) But I currently don't know what's best. Therefore I've asked @annejan to review this as well..

**Comment by annejan** [comment]
Unfortunately most apps use the deprecated function currently.

I could re-write all of them, or we could keep this 'wrapper' function . .

**Comment by basvs** [comment]
Let's keep the wrapper function then.. Missed chance for a cleaner API.

**Review by annejan — COMMENTED** [review]
I have removed the deprecated function from wiki . .

Will remove from apps tomorrow and merge!

**Comment by annejan** [comment]
Updated all apps in Hatchery and info on wiki

**Pull request merged**
